scalar Date

scalar JSON

type GraphQLResult {
  data: JSON
  errors: JSON
  extensions: JSON
  status: Int!
}

type Query {
  query(endpoint: String!, query: String!, variables: JSON): GraphQLResult!
}

type Mutation {
  mutate(endpoint: String!, mutation: String!, variables: JSON): GraphQLResult!
}

type QueryEvent {
  endpoint: String!
  query: String!
  variables: JSON
}

type MutateEvent {
  endpoint: String!
  mutation: String!
  variables: JSON
}

type Subscription {
  onQuery: QueryEvent!
  onMutate: MutateEvent!
}
