query allPeople {
  query(
    endpoint: "http://localhost:8051/graphql"
    query: "query allPeople { allPeople { id name givenName familyName dateOfBirth }}"
  ) {
    data
    errors
    extensions
    status
  }
}

mutation addPerson {
  mutate(
    endpoint: "http://localhost:8051/graphql"
    mutation: "mutation addPerson($id: ID, $name: String!, $givenName: String!, $familyName: String!, $dateOfBirth: Date!) { addPerson(input: { id: $id name: $name givenName: $givenName familyName: $familyName dateOfBirth: $dateOfBirth })}"
    variables: "{\"id\":\"p1\",\"name\":\"bob smith\",\"givenName\":\"bob\",\"familyName\":\"smith\",\"dateOfBirth\":\"01/01/2001\"}"
  ) {
    data
    errors
    extensions
    status
  }
}

query bobSmith {
  query(
    endpoint: "http://localhost:8051/graphql"
    query: "query person($id: ID!) { person(id: $id){ id name givenName familyName dateOfBirth } }"
    variables: "{\"id\":\"p1\"}"
  ) {
    data
    errors
    extensions
    status
  }
}

query select {
  selectGraphQLResultData(
    result: {
      data: "{\"person\":{\"id\":\"p1\",\"name\":\"bob smith\",\"givenName\":\"bob\",\"familyName\":\"smith\",\"dateOfBirth\":\"01/01/2001\"}}"
      status: 200
    }
  )
  selectGraphQLResultStatus(result: { status: 500 })
}
