# Write your query or mutation here
query allPeople {
  query(
    endpoint: "http://localhost:8051/graphql"
    query: "query allPeople { allPeople { id name givenName familyName dateOfBirth }}"
  ) {
    data
    errors
    extensions
    status
  }
}

mutation addPerson {
  mutate(
    endpoint: "http://localhost:8051/graphql"
    mutation: "mutation addPerson { addPerson(input: { id: \"p1\" name: \"bob smith\" givenName: \"bob\" familyName: \"smith\" dateOfBirth: \"01/01/2001\" })}"
  ) {
    data
    errors
    extensions
    status
  }
}
